#!/bin/bash

# Taken from https://github.com/mathiasbynens/dotfiles/blob/master/.brew
# By way of proxy through https://github.com/jacobian/dotfiles/blob/master/.brew

# Tap some kegs
brew tap homebrew/versions
brew tap phinze/homebrew-cask
brew tap homebrew/science

# Make sure we're up-to-date
brew update

# Now all the awesome stuff. Unfortunately the order here kinda matters
# because of how things build. Ick. So, prereqs:
brew install coreutils
brew install sqlite
brew install readline

# Other stuff:
brew install ack
brew install apple-gcc42
brew install ascii
brew install autoconf
brew install automake
brew install cmake
brew install cowsay
brew install emacs
brew install erlang
brew install ffmpeg
brew install freetype
brew install gdbm
brew install gettext
brew install gist
brew install git-flow
brew install gnu-time
brew install graphviz
brew install gpg
brew install heroku-toolbelt
brew install hub
brew install jmeter
brew install jpeg
brew install lftp
brew install libevent
brew install libgpg-error
brew install libffi
brew install libksba
brew install libmemcached
brew install libpng
brew install libsvg
brew install libtool
brew install libyaml
brew install markdown
brew install mcrypt
brew install memcached
brew install mercurial
brew install mongodb
brew install mtr
brew install mysql
brew install nmap
brew install node
brew install octave --without-docs
brew install openssl
brew install ossp-uuid
brew install phantomjs
brew install pidof
brew insatll pkg-config
brew install png2ico
brew install pngquant
brew install pwgen
brew install pypy
brew install python
brew install python3
brew install python32
brew install rabbitmq
brew install redis
brew install sbcl
brew install selecta
brew install solr
brew install ssh-copy-id
brew install tig
brew install tmux
brew install tree
brew install watch
brew install wget
brew install youtube-dl
brew install zmq

# Native apps
brew install brew-cask
function installcask() {
    if brew cask info "${@}" | grep "Not installed" > /dev/null; then
        brew cask install "${@}"
    else
        echo "${@} is already installed."
    fi
}

installcask adium
installcask alfred
installcask all2mp3
installcask arq
installcask bartender
installcask bittorrent-sync
installcask charles
installcask coconutbattery
installcask dropbox
installcask emacs
installcask fantastical
installcask firefox
installcask flickr-uploadr
installcask fluid
installcask github
installcask gitx-l
installcask google-chrome
installcask google-drive
installcask handbrake
installcask heroku-toolbelt
installcask hipchat
installcask imageoptim
installcask iterm2
installcask kaleidoscope
installcask licecap
installcask liteicon
installcask mailplane
installcask menumeters
installcask mou
installcask nvalt
installcask peepopen
installcask pgadmin3
installcask postgres
installcask propane
installcask rdio
installcask screenhero
installcask sequel-pro
installcask slate
installcask smcfancontrol
installcask sourcetree
installcask sqwiggle
installcask unrarx
installcask vagrant
installcask versions
installcask vlc
installcask virtualbox
installcask xquartz
installcask zooom
