#!/bin/sh
set -e

pipsi install ansible
pipsi install autopep8
pipsi install bpython
pipsi install cookiecutter
pipsi install fabric
pipsi install flake8
pipsi install glances
pipsi install httpie
pipsi install --python python3 invoke
pipsi install ipython
pipsi install lice
pipsi install pygments
pipsi install python-fu
pipsi install sr
pipsi install supervisor
pipsi install tox
pipsi install twine
pipsi install unp

pipsi install 'git+git://github.com/pre-commit/pre-commit-hooks.git#egg=pre-commit-hooks'
pipsi install 'https://pypi.python.org/packages/source/s/s3cmd/s3cmd-1.5.0-alpha3.tar.gz#egg=s3cmd'
