#!/bin/bash

pipsi install ansible
pipsi install bpython
pipsi install cookiecutter
pipsi install fabric
pipsi install flake8
pipsi install httpie
pipsi install invoke
pipsi install lice
pipsi install tox

pipsi install 'git+git://github.com/pre-commit/pre-commit-hooks.git#egg=pre-commit-hooks'
